cmake_minimum_required(VERSION 3.25)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")
project(FrameyApp LANGUAGES CXX RC)
set(CMAKE_CXX_FLAGS_RELEASE "-Os -DNDEBUG")
add_executable(FrameyApp WIN32 src/main.cpp app.rc)
target_compile_options(FrameyApp PRIVATE -std=c++2c -fno-ident -Wall)
target_link_options(FrameyApp PRIVATE -fuse-ld=lld -Wl,/OPT:REF,/OPT:ICF "-Wl,/MANIFESTINPUT:${CMAKE_SOURCE_DIR}/app.manifest")
target_link_libraries(FrameyApp PRIVATE user32 gdi32 comctl32 shell32 uxtheme dwmapi)
set_source_files_properties(app.rc PROPERTIES OBJECT_DEPENDS "${CMAKE_SOURCE_DIR}/payload/payload.tar;${CMAKE_SOURCE_DIR}/assets/framey.ico;${CMAKE_SOURCE_DIR}/app.manifest")
