cmake_minimum_required(VERSION 3.25)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")
if(WIN32)
  project(FrameyApp LANGUAGES CXX RC)
else()
  project(FrameyApp LANGUAGES CXX)
endif()
set(CMAKE_CXX_FLAGS_RELEASE "-Os -DNDEBUG")
set(SOURCES src/main.cpp)
if(WIN32)
  list(APPEND SOURCES app.rc)
endif()
add_executable(FrameyApp ${SOURCES})
target_include_directories(FrameyApp PRIVATE generated)
target_compile_options(FrameyApp PRIVATE -std=c++2c -fno-rtti -ffunction-sections -fdata-sections -Wall)
if(WIN32)
  target_link_options(FrameyApp PRIVATE -fuse-ld=lld -Wl,/OPT:REF,/OPT:ICF)
  target_link_libraries(FrameyApp PRIVATE ws2_32 shell32 -Wl,/MANIFEST:NO)
  set_source_files_properties(app.rc PROPERTIES OBJECT_DEPENDS "${CMAKE_SOURCE_DIR}/assets/framey.ico;${CMAKE_SOURCE_DIR}/app.manifest")
elseif(APPLE)
  target_compile_options(FrameyApp PRIVATE -mmacosx-version-min=13.3)
  target_link_options(FrameyApp PRIVATE -mmacosx-version-min=13.3 -Wl,-dead_strip)
else()
  find_package(Threads REQUIRED)
  target_link_libraries(FrameyApp PRIVATE Threads::Threads)
  target_link_options(FrameyApp PRIVATE -static -Wl,--gc-sections -s)
endif()
